[tool.poetry]
name = "parser-vacancy"
version = "0.1.0"
description = ""
authors = ["gvia <gritcaev.vv@gmail.com>"]
readme = "README.md"
packages = [{include = "parser_vacancy"}]

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
